// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityBusiness;

#nullable disable

namespace UniversityBusiness.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    partial class UniversityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityBusiness.Specialization", b =>
                {
                    b.Property<int>("SpecializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SpecializationId"));

                    b.Property<string>("SpecializationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SpecializationId");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            SpecializationId = 1,
                            SpecializationName = "IT"
                        },
                        new
                        {
                            SpecializationId = 2,
                            SpecializationName = "BIS"
                        },
                        new
                        {
                            SpecializationId = 3,
                            SpecializationName = "MATH"
                        });
                });

            modelBuilder.Entity("UniversityBusiness.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            SpecializationId = 1,
                            StudentName = "Tran Thi Thu"
                        },
                        new
                        {
                            StudentId = 2,
                            SpecializationId = 1,
                            StudentName = "Hoang Van Bao"
                        },
                        new
                        {
                            StudentId = 3,
                            SpecializationId = 2,
                            StudentName = "Ngo Thi Ha"
                        },
                        new
                        {
                            StudentId = 4,
                            SpecializationId = 2,
                            StudentName = "Tong Van Dat"
                        },
                        new
                        {
                            StudentId = 5,
                            SpecializationId = 3,
                            StudentName = "Hoang Bach"
                        },
                        new
                        {
                            StudentId = 6,
                            SpecializationId = 3,
                            StudentName = "Nong Thi Thom"
                        },
                        new
                        {
                            StudentId = 7,
                            SpecializationId = 3,
                            StudentName = "Hoang Lan"
                        },
                        new
                        {
                            StudentId = 8,
                            SpecializationId = 1,
                            StudentName = "Le Viet Tinh"
                        });
                });

            modelBuilder.Entity("UniversityBusiness.Student", b =>
                {
                    b.HasOne("UniversityBusiness.Specialization", "Specialization")
                        .WithMany("Students")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("UniversityBusiness.Specialization", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
